Open-Eye-Im-Developer/MoGakGo-BE

- build.gradle
> [CHORE] Spring Boot Data Redis 의존 추가

- src/main/java/io/oeid/mogakgo/domain/project/domain/Project.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/enums/ProjectStatus.java
- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
- #10 
- 현재 진행중
- `project` 도메인 관련 부분만 먼저 PR
> [FEAT] Project 도메인 개발 (#10) (진행중)

- src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode500.java
- src/main/java/io/oeid/mogakgo/exception/dto/ErrorResponse.java
- src/main/java/io/oeid/mogakgo/exception/exceptionClass/CustomException.java
[FEAT] 공통 Error Handler, code 기능 구현
- close #7 
error code 는 노션에서 관리합니다.
[error code](https://www.notion.so/prgrms/error-code-70f17c3c78384684a365ff3afc497765?pvs=4)
> [FEAT] 공통 Error Handler, code 기능 구현

- build.gradle
- firebase-admin 의존을 추가했습니다.
- close #36
> [CHORE] firebase-admin 의존성 추가

- build.gradle
- src/main/java/io/oeid/mogakgo/common/base/BaseTimeEntity.java
- src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
- src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfig.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
- src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtHelper.java
- src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/ProjectTag.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/CreatorInfo.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/MeetingInfo.java
- src/main/java/io/oeid/mogakgo/domain/project/exception/ProjectException.java
- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectCreateReq.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectTagCreateReq.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectIdRes.java
- src/main/java/io/oeid/mogakgo/domain/user/exception/UserException.java
- src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
- src/main/java/io/oeid/mogakgo/exception/dto/ErrorResponse.java
> Feat/#32 project card 생성, 삭제 구현

- Dockerfile
> [CHORE] CD 자동화 구축을 위한 Dockerfile 작성

- .github/workflows/cd_gradle.yml
> [CHORE] CD 자동화 구축

- .github/workflows/cd_gradle.yml
> [FIX] 오타 수정

- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/vo/MeetingInfo.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectCreateReq.java
- src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java
* [FIX] 현재 혹은 미래로 시간 설정 할 수 있게 유효성 검증 수정
* [FEAT] 5분 단위로 시간 설정 할 수 있게 변경
* [FIX] 줄바꿈 문자 변경
* [FIX] json 줄바꿈 문자 인식 오류로 인한 seperator 변경
- close
> Fix/#68 project time bug (#71)

- src/main/java/io/oeid/mogakgo/domain/achievement/domain/Achievement.java
- src/main/java/io/oeid/mogakgo/domain/achievement/domain/enums/AchievementType.java
- Achievement 도메인을 작성했습니다.
- close #20 
- RDS에 작성되어 있던 Achievement 기반으로 작성했습니다 :D
> Feat/#20 Achievement Domain

- src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCard.java
- src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCardLike.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardJpaRepository.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustom.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
> [FEAT] ProfileCard와 ProfileCardLike 엔티티 구현

- .github/workflows/cd_gradle.yml
- .github/workflows/ci_gradle.yml
- Firebase secret 적용을 위한 CI, CD 수정
- close #87
> [REFACT] ci, cd 수정

- src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserSignUpApiRequest.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserProfileCardApiResponse.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
- 회원 가입시 Github에서 갖고 온 정보를 확인하기 위한 기능입니다.
- close #90
> Feat/#90 회원 가입시 유저 조회 기능 추가

- src/main/java/io/oeid/mogakgo/domain/achievement/domain/enums/AchievementType.java
- src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/projectJoinRequestRes.java
- src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
- 페이지네이션 정보 전달 누락 수정 
- 배치사이즈 반영으로 N+1 해결
- 
- close #93 
배치 사이즈 동작 방식 정리해서 올리겠습니다!
> Feat/#93 프로젝트 요청 조회 오류 수정

- src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinRequestSwagger.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectJoinRequestErrorExamples.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
> [FEAT] 이미 매칭을 보낸 사용자의 추가 매칭 불가를 검사하는 유효성 검사 기능 개발

- src/main/java/io/oeid/mogakgo/common/swagger/template/OAuth2Swagger.java
- src/main/java/io/oeid/mogakgo/domain/auth/presentation/OAuth2Controller.java
- 로그인 응답을 클라이언트 URI로 반환하는 로직을 구현했습니다.
- close #103
- application.yml v6에 값이 추가되었습니다! 확인해주세요!!!
> Bug/#103 OAuth2 로그인 응답 반환

- src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
- src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinReqSwagger.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerMatchingErrorExamples.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
- src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
- src/main/java/io/oeid/mogakgo/domain/matching/domain/entity/Matching.java
- src/main/java/io/oeid/mogakgo/domain/matching/domain/entity/enums/MatchingStatus.java
- src/main/java/io/oeid/mogakgo/domain/matching/exception/MatchingException.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingId.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/enums/ProjectStatus.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/ProjectJoinRequestController.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
- close #86 
리뷰 보내기 기능 완성 후 추가 필요
> [FEAT] 매칭 취소 기능 개발

- src/main/java/io/oeid/mogakgo/common/base/CursorPaginationResult.java
CursorPaginationResult 내부 리스트 변경 가능한 타입으로 변경
- close #112 
#108 변경 필요
> [BUG] CursorPaginationResult 내부 리스트 변경 가능한 타입으로 변경

- src/main/java/io/oeid/mogakgo/common/swagger/template/NotificationSwagger.java
- src/main/java/io/oeid/mogakgo/domain/auth/oauth/OAuth2AuthenticationSuccessHandler.java
- src/main/java/io/oeid/mogakgo/domain/notification/application/NotificationService.java
- src/main/java/io/oeid/mogakgo/domain/notification/application/dto/req/NotificationCreateRequest.java
- src/main/java/io/oeid/mogakgo/domain/notification/application/dto/res/NotificationCreateResponse.java
- src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
- src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationCustomRepository.java
- src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationCustomRepositoryImpl.java
- src/main/java/io/oeid/mogakgo/domain/notification/infrastructure/NotificationJpaRepository.java
- src/main/java/io/oeid/mogakgo/domain/notification/presentation/NotificationController.java
- src/main/java/io/oeid/mogakgo/domain/notification/presentation/dto/res/NotificationPublicApiRes.java
- src/main/java/io/oeid/mogakgo/domain/notification/presentation/vo/NotificationDataVo.java
- src/main/java/io/oeid/mogakgo/domain/notification/presentation/vo/NotificationSenderVo.java
- pull noti에 대한 pagination을 적용한 읽기를 구현했습니다.
- close #50 
- Notification 도메인 변경으로 인한 RDS 수정 완료했습니다!
> Feat/#50 Pull Notification Pagination 적용

- src/main/java/io/oeid/mogakgo/domain/project_join_req/application/dto/req/ProjectJoinCreateReq.java
> [FIX] 유저 프로젝트 조인 요청 역직렬화 오류 해결

- src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
- src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
- src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
- WantedJob 와 DevelopLanguage에 대한 중복 로직을 전면 수정했습니다!
- close #116
> Bug/#116 매핑 테이블 중복 로직 수정

- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
> [MERGE] develop을 main에 반영

- src/main/java/io/oeid/mogakgo/core/configuration/SchedulerConfig.java
- src/main/java/io/oeid/mogakgo/scheduler/FinishedProjectScheduler.java
- src/main/resources/sql/finished_matched_project_after_12.sql
- src/main/resources/sql/finished_pending_project_after_12.sql
- src/main/resources/sql/rejected_project_request_about_finished_project.sql
sql문 실행으로 스케쥴러 구현
- close #133 
추후 리뷰가 개발되어 프로젝트 상태 변경에 따라 리뷰를 보내줘야 하는 기능이 개발 될 시 코드 변경.
> [FEAT] sql문 실행으로 스케쥴러 구현

- .github/workflows/cd_gradle.yml
> develop to main

- build.gradle
- src/main/java/io/oeid/mogakgo/domain/auth/presentation/AuthController.java
- src/main/java/io/oeid/mogakgo/domain/auth/presentation/dto/req/AuthReissueRequest.java
- MongoDB 의존을 추가했습니다.
- WebSocket 의존을 추가했습니다.
- close #163 
- close #165 
- application.yml v8에 mongoDB 관련 내용을 추가했습니다. 갱신해주세요!
> [CHORE] websocket, mongoDB 의존 추가

- src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardLikeSwagger.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProfileCardErrorExamples.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProfileCardLikeErrorExamples.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
- src/main/java/io/oeid/mogakgo/domain/cert/application/CertService.java
- src/main/java/io/oeid/mogakgo/domain/geo/application/GeoService.java
- src/main/java/io/oeid/mogakgo/domain/geo/domain/enums/Region.java
- src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardLikeService.java
- src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
- src/main/java/io/oeid/mogakgo/domain/profile/application/dto/req/UserProfileCardReq.java
- src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCard.java
- src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCardLike.java
- src/main/java/io/oeid/mogakgo/domain/profile/exception/ProfileCardException.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardJpaRepository.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeJpaRepository.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeRepositoryCustom.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/profile/presentation/ProfileCardLikeController.java
- src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/req/UserProfileLikeCancelAPIReq.java
- src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/req/UserProfileLikeCreateAPIReq.java
- src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
- src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/domain/entity/ProjectJoinRequest.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
- src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
- src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java
- close #144 
- close #157 
예전에 진행했던 DDD 스터디 내용을 기반으로 도메인 모델을 리팩토링해보았습니다! 혹시 제가 미처 고려하지 못한 부분이나 더 좋은 아이디어 등이 있다면 마음껏 피드백 부탁드립니다~!
(아직 수정한 부분에 대한 테스트는 진행하지 않아서 오늘 자정 중으로 API 전체적으로 테스트해보고 고쳐야 할 부분 있으면 수정할 예정입니다🤫 코드 리뷰와 별개로 빠르게 테스트 완료한 다음에 리뷰 끝나면 제가 develop에 머지하도록 하겠습니닷)
+ API 테스트 완료✅
> [REFACT] 전반적인 API 리팩토링, 프로필 카드에 대한 찔러보기 요청 취소 API 기능 개발

- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
> [FIX] sql문 상태 이름 오류 수정

- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
> [FIX] sql문 상태 이름 오류 수정 (#169)

- src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserMatchingStatus.java
현재 회원 매칭 상태 확인하는 기능 구현
- close #161
> [FEAT] 현재 회원 매칭 상태 확인하는 기능 구현

- src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfig.java
- Reissue Security Config 옵션을 수정했습니다 (`authenticated()` -> `permitAll()`)
- close #184
> Bug/#184 Reissue Authroization

- src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfig.java
- Reissue가 정상적으로 작동하지 않는 현상 수정
> develop to main (HOTFIX)

- src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/Achievement.java
- src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/UserAchievement.java
- src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/UserActivity.java
- src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/enums/ActivityType.java
- src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/enums/RequirementType.java
- src/main/java/io/oeid/mogakgo/domain/achievement/domain/enums/AchievementType.java
- src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/AchievementJpaRepository.java
- src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
- src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
> Feat/#182 업적 도메인 구현

- build.gradle
- src/main/resources/db/migration/V1__init.sql
- close #77 
- [spring에서 flyway 적용하기](https://yeongchan1228.tistory.com/134)
- [spring boot flyway 적용](https://mindybughunter.com/spring-boot-flyway-%EC%A0%81%EC%9A%A9%EA%B8%B0/)
- [flyway repair](https://www.baeldung.com/spring-boot-flyway-repair)
> [FEAT] 데이터베이스 스키마에 대한 형상 관리를 위한 Flyway 적용

- src/main/resources/db/migration/V1__init.sql
> [BUG] 초기 데이터베이스 스키마 flyway 적용에서 sql 컬럼명 오타 수정

- src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardLikeSwagger.java
- src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
- src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
- src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
> [REFACT] 사용자의 '찔러보기' 요청 제약조건 제거 관련 리팩토링

- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
- src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserProfileResponse.java
- src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java
- 유저 프로필 조회시 업적 ID도 같이 조회할 수 있도록 추가했습니다.
- close #232
> [REFACT] 유저 프로필 조회 업적 ID 추가

- src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
- 채팅방 상세 정보 조회 수정
- close #234
> [BUG] 채팅방 상세 정보 조회 수정

- src/main/java/io/oeid/mogakgo/domain/achievement/presentation/AchievementController.java
> [REFACT] API 엔드포인트 수정

- src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
- src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
- src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
- src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
> [REFACT] 프로젝트 매칭 히스토리 조회 시, 매칭 상태 필터링 추가

- src/main/java/io/oeid/mogakgo/domain/notification/application/FCMNotificationService.java
- src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java
- src/main/java/io/oeid/mogakgo/domain/notification/domain/enums/FCMNotificationType.java
- src/main/java/io/oeid/mogakgo/domain/notification/domain/enums/NotificationMessage.java
- src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
- src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailInfoAPIRes.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
> main <- develop (alpha .2)

- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/res/UserProfileLikeInfoAPIRes.java
> [REFACT] 사용자의 '찔러보기' 요청 리스트 조회 API 리팩토링

- src/main/java/io/oeid/mogakgo/domain/notification/application/FCMNotificationService.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardLikeRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/res/UserProfileLikeInfoAPIRes.java
> main <- develop (bug fix)

- src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
> [BUG] 사용자의 업적 상세 조회가 제대로 작동하지 않아요!

- src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
- src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
- src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
- src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingProjectRes.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
현재 매칭 된 프로젝트 정보 가져오기 기능
- close #279
> [FEAT] 현재 매칭 된 프로젝트 정보 가져오기 기능

- src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
- src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
- src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
- src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
- src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingProjectRes.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
[FEAT] 현재 매칭 된 프로젝트 정보 가져오기 기능 (#283)
- close #279
> [FEAT] 현재 매칭 된 프로젝트 정보 가져오기 기능 (#283)

- src/main/java/io/oeid/mogakgo/core/configuration/WebSocketConfig.java
> [BUG] 웹 소켓 활성화를 위한 @EnableWebSocket 추가

- src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingProjectRes.java
현재 매칭 된 프로젝트 정보 가져오기 기능 스키마 수정
- close #294
> [REFACT] 현재 매칭 된 프로젝트 정보 가져오기 기능 스키마 수정

- src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
- 매칭 요청시 프로젝트 제안자에게 PULL 알림 전달 로직을 추가했습니다.
- close #292
> Feat/#292 매칭 요청시 PULL 알림 전달 기능 추가

- src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingProjectRes.java
- src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
[REFACT] 현재 매칭 된 프로젝트 정보 가져오기 기능 스키마 수정 (#296)
- close
> [REFACT] 현재 매칭 된 프로젝트 정보 가져오기 기능 스키마 수정 (#296)

- src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
- src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementSocketService.java
> [REFACT] 소켓 연결 후 세션으로 메시지 전송하는 로직 리팩토링

- src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementSocketService.java
- src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/session/AchievementSessionRepository.java
> [REFACT] session 저장 로직 수정 및 로그 추가

- src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
- src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/AchievementMessage.java
> [REFACT] 업적 관련 소켓 통신 시, 응답 타입 DTO 수정

- src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
- 달성 업적에 대한 PULL 알림 기능 추가
- close #295
> FEAT/#295 달성 업적에 대한 PULL 알림 기능 추가

- src/main/java/io/oeid/mogakgo/common/swagger/template/AchievementSwagger.java
- src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
- src/main/java/io/oeid/mogakgo/domain/achievement/presentation/AchievementController.java
- src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/AchievementInfoAPIRes.java
> [FEAT] 특정 업적 상세 정보 조회 API 개발

- src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardPublicSwagger.java
- src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
- src/main/java/io/oeid/mogakgo/core/configuration/SecurityConfig.java
- src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustom.java
- src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/profile/presentation/ProfilePublicController.java
- src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
- src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
> alpha .3 main <- develop

- src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
> [FEAT] 사용자의 업적 달성 여부 검종 메서드 수정

- src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
- src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/AchievementJpaRepository.java
> [REFACT] 업적 이력 메시지 전송을 위한 검증 로직 오류 수정

- src/main/java/io/oeid/mogakgo/common/aop/AchievementEventAspect.java
- src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
- src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
> [REFACT] 누적 업적에 대한 progressCount 조회 로직 수정, 업적 달성을 위한 검증 로직 리팩토링

- src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
> [BUG] 사용자의 업적 진행도를 포함한 업적 상세 조회 리스트에서 누적되는 업적에 대한 로직 수정
