src/main/java/io/oeid/mogakgo/domain/geo/domain/enums/Region.java

- close #53 
- 기본적으로 `depth1` (시 개념), `depth2` (구 개념), `areaCode` (법정동 코드) 이외에 필요한 데이터가 있을까 고민했는데
딱히 없는 것 같다고 판단했습니다. 추가로 고려하거나 수정할 부분이 있다면 피드백 부탁드립니다~🙇🏻‍♀️

[FEAT] 서비스 지역에 대한 법정동 코드 관리 위한 Enum 구현

---

build.gradle
src/main/java/io/oeid/mogakgo/MogakGoApplication.java
src/main/java/io/oeid/mogakgo/core/properties/KakaoProperties.java
src/main/java/io/oeid/mogakgo/domain/geo/application/GeoService.java
src/main/java/io/oeid/mogakgo/domain/geo/feign/KakaoFeignClient.java
src/main/java/io/oeid/mogakgo/domain/geo/feign/dto/AddressDocument.java
src/main/java/io/oeid/mogakgo/domain/geo/feign/dto/AddressInfoDto.java

Kakao Map API를 OpenFeign 라이브러리를 이용해서 호출하고, 쿼리 파라미터로 입력한 좌표에 대한 '구' 법정동 코드를 추출하는 메서드 구현
`getAreaCodeAboutCoordinates()`
`getAddressInfoAboutAreaCode()`
`generateKey()`
`extractAreaCode()`  
- close #56 
- 외부 API를 호출하는 라이브러리를 RestTemplate을 사용하려다가 Feign Client로 외부 API를 호출하는 방식이 훨씬 가독성과 사용 측면에서 깔끔하다고 판단해서 사용해보았습니다. 참고할만한 레퍼런스를 같이 올려놓을게요!
[참고자료1](https://vmpo.tistory.com/109)
[참고자료2](https://jie0025.tistory.com/531)

[FEAT] Kakao Map API를 이용해 좌표 - 법정동 코드 변환 기능 개발

---

.github/workflows/ci_gradle.yml

[CHORE] CI 자동화 구축

---

src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
src/main/java/io/oeid/mogakgo/domain/project/domain/entity/enums/ProjectStatus.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/domain/entity/ProjectJoinRequest.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/domain/entity/enums/RequestStatus.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestJpaRepository.java
src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java

Feat/#69 프로젝트 취소 기능 구현

---

src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectJpaRepository.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java

[FEAT] 프로젝트 카드 동적 쿼리 조회 로직 구현, 커서 기반 페이지네이션 적용

---

src/main/java/io/oeid/mogakgo/domain/notification/application/NotificationService.java
src/main/java/io/oeid/mogakgo/domain/notification/application/dto/req/NotificationCreateRequest.java
src/main/java/io/oeid/mogakgo/domain/notification/application/dto/res/NotificationCreateResponse.java
src/main/java/io/oeid/mogakgo/domain/notification/domain/Notification.java

- Pull Notification 생성 로직을 구현했습니다.
- close #51

FEAT/#51 Pull Notification 생성 구현

---

src/main/java/io/oeid/mogakgo/common/base/CursorPaginationInfoReq.java
src/main/java/io/oeid/mogakgo/common/base/CursorPaginationResult.java
src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerProjectErrorExamples.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/req/ProjectCreateReq.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/exception/ProjectJoinRequestException.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestJpaRepository.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/projectJoinRequestRes.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPreviewRes.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java

- CursorPaginationInfoReq , CursorPaginationResult<T> 를 통해 공통 페이지네이션 req, res 생성
- CursorPaginationResult 내부에서 hasNext 계산하는 로직 구현. 정적 팩토리 메서드 별로 달라짐
- fromDataWithExtraItemForNextCheck() 를 통해 내부에서 계산
- fromDataWithHasNext() 는 외부에서 값을 받음
- close #33 
- 페이지네이션 sort 관련 사항 아직 반영 X

[FEAT] 프로젝트 참가 요청 조회 기능 구현

---

src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
src/main/java/io/oeid/mogakgo/domain/achievement/domain/enums/AchievementType.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastruture/ProjectJoinRequestRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/projectJoinRequestRes.java
src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserSignUpApiRequest.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserPublicApiResponse.java

develop 반영 

---

src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinRequestSwagger.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/ProjectJoinRequestController.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java

- close #43 
- 추후에 리팩토링할 예정입니다! 우선은 기능 구현에 초점을 두고 개발했습니다.

[FEAT] 사용자가 보낸 프로젝트 매칭 요청 리스트 조회 API 개발

---

src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
src/main/java/io/oeid/mogakgo/domain/geo/domain/enums/Region.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDensityRankRes.java

지역별 프로젝트 밀집도 랭크 조회 기능
- close #40 
현재 기본 랭킹 limit 는 3.
최소 프로젝트가 1개 이상 있는 지역을 대상으로 랭크를 집계하였고, 
만약 기본 랭킹 limit 보다 돌아온 지역 수가 적다면 (ex. limit 3. 1개이상 프로젝트가 있는 지역이 3개 미만 일때)
기본 지역을 추가로 넣어서 기본 랭킹 limit 을 맞춰 return 한다.

[FEAT] 지역별 프로젝트 밀집도 랭크 조회 기능

---

src/main/java/io/oeid/mogakgo/common/base/CursorPaginationResult.java
src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
src/main/java/io/oeid/mogakgo/domain/profile/domain/entity/ProfileCard.java
src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java

- close #108 
- `List<T> Data` 불변 리스트에 대해서 랜덤 정렬 동작 수행 시, 오류가 발생하고, queryDsl에서 랜덤 정렬이 불가능한 점을 고려해보았을 때, 조회한 mutable List로 복제해서 랜덤 정렬을 한 후, setter를 사용하도록 했는데 setter 사용을 지양할 수 있는 다른 방법은 없을지, 더 좋은 해결 방법은 없는지 피드백 부탁드립니다~

[Bug] 프로젝트, 프로필 카드 랜덤 리스트 조회 API 동작 오류 해결, 불변 리스트 정렬 불가 오류 해결

---

src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java

[REFACT] 프로젝트 생성자에 대해 해당 프로젝트에 대한 매칭 요청 불가 에러코드 변경 (403 -> 400)

---

src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java

프로젝트 취소 시 요청들 모두 취소하기 구현
- close #111

[FIX] 프로젝트 취소 시 요청들 모두 취소하기 구현

---

src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java

매칭 생성 시 해당 프로젝트 다른 요청들 거절하는 로직 구현
- close #104

[FIX] 매칭 생성 시 해당 프로젝트 다른 요청들 거절하는 로직 구현

---

src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java

[BUG] 프로젝트, 프로필 카드 리스트 조회할 때, 업적 조회 시 발생하는 NPE 해결

---

src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java

[REFACT] 프로젝트 생성일 유효성 검사, 프로젝트 상태 유효성 검사, 프로젝트 상태 필드 추가

---

src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectJoinReqSwagger.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/application/ProjectJoinRequestService.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestJpaRepository.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java

스웨거 문서 페이지네이션 정보 누락 오류 수정
- 페이지네이션 정보가 누락 되었습니다. 쿼리 파라미터로 받는 정보들은 메서드 위에  @Parameters 로 선언 해줘야만 스웨거 문서 상에서 볼 수 있습니다.
- 제네릭을 사용해서 return value 를 명시하는 컨트롤러는 content 를 따로 지정하지 않아야 제대로 return 값이 나타납니다. 현재 경우도 동일한 경우로 content 지정한 부분을 제거하였습니다.
프로젝트 요청 보내기 유효성 검사 쿼리 오류 수정
- 본인이 보낸 대기상태의 요청이 있는 경우 다른 프로젝트에 요청을 보낼 수 없습니다. 해당 유효성 검사에서 'PENDING' 상태의 요청 존재 여부만 체크해야 하는데 모든 상태의 요청 존재 여부를 체크해 오류가 발생 하였습니다. 따라서 쿼리에 'PENDING' 상태의 요청만 가져오게 수정 하였습니다.
- close

[FIX] Api 오류들 수정

---

src/main/java/io/oeid/mogakgo/domain/cert/application/CertService.java
src/main/java/io/oeid/mogakgo/domain/geo/application/GeoService.java
src/main/java/io/oeid/mogakgo/domain/geo/application/feign/KakaoFeignClient.java
src/main/java/io/oeid/mogakgo/domain/geo/application/feign/dto/AddressDocument.java
src/main/java/io/oeid/mogakgo/domain/geo/application/feign/dto/AddressInfoDto.java
src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode401.java

* [REFACT] openFeign 관련 패키지를 Geo 하위 패키지로 이동
* [FEAT] @Transactional 어노테이션 추가
* [FEAT] 탈퇴한 사용자의 프로필 카드를 조회할 수 없도록 필터링 추가
- close

[MERGE] develop을 main에 반영

---

src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailAPIRes.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java

[REFACT] 프로젝트 카드 랜덤 리스트 조회 API에서 프로젝트 상태 필드를 추가로 전달하도록 수정, queryDSL warn 해결

---

src/main/java/io/oeid/mogakgo/common/base/CursorPaginationInfoReq.java
src/main/java/io/oeid/mogakgo/common/swagger/template/MatchingSwagger.java
src/main/java/io/oeid/mogakgo/domain/matching/application/MatchingService.java
src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingJpaRepository.java
src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/matching/infrastructure/MatchingRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/matching/presentation/MatchingController.java
src/main/java/io/oeid/mogakgo/domain/matching/presentation/dto/MatchingHistoryRes.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java

Feat/#135 내 매칭 기록 조회하기

---

src/main/java/io/oeid/mogakgo/domain/chat/application/dto/res/ChatRoomPublicRes.java
src/main/java/io/oeid/mogakgo/domain/chat/infrastructure/ChatRoomCustomRepositoryImpl.java
src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java

- 채팅방 조회 오류 수정을 진행했습니다.
- close #187

Bug/#187 chatroom 조회 오류 수정

---

src/main/java/io/oeid/mogakgo/domain/project/domain/entity/Project.java
src/main/java/io/oeid/mogakgo/domain/review/application/ReviewService.java
src/main/java/io/oeid/mogakgo/domain/review/application/dto/req/ReviewCreateReq.java
src/main/java/io/oeid/mogakgo/domain/review/application/dto/res/ReviewCreateRes.java
src/main/java/io/oeid/mogakgo/domain/review/domain/Review.java
src/main/java/io/oeid/mogakgo/domain/review/domain/enums/ReviewRating.java
src/main/java/io/oeid/mogakgo/domain/review/exception/ReviewException.java
src/main/java/io/oeid/mogakgo/domain/review/infrastructure/ReviewJpaRepository.java
src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java

- 리뷰 생성 기능을 구현했습니다.
- 리뷰 작성 완료시 결과에 따른 잔디력 증감이 바로 반영되도록 잔디력 증감 알고리즘을 구현했습니다.
- close #141

Feat/#141 리뷰 추가 기능 구현

---

src/main/java/io/oeid/mogakgo/common/swagger/template/UserSwagger.java
src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerAchievementErrorExamples.java
src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserAchievementErrorExamples.java
src/main/java/io/oeid/mogakgo/core/properties/swagger/error/SwaggerUserErrorExamples.java
src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/UserAchievement.java
src/main/java/io/oeid/mogakgo/domain/achievement/exception/AchievementException.java
src/main/java/io/oeid/mogakgo/domain/achievement/exception/UserAchievementException.java
src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementJpaRepository.java
src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
src/main/java/io/oeid/mogakgo/domain/user/application/dto/res/UserUpdateRes.java
src/main/java/io/oeid/mogakgo/domain/user/domain/User.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/req/UserAchievementUpdateApiRequest.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserAchievementUpdateApiResponse.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserUpdateApiRes.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode400.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode403.java
src/main/java/io/oeid/mogakgo/exception/code/ErrorCode404.java

- close #137 
- 사용자가 대표 업적을 변경하는 과정에서, 이미 대표 업적으로 등록되어 있는 업적을 동일하게 변경하려고 할 때 어떤 식으로 처리를 하는 것이 좋을지 고민이 됩니다.
1. User 엔티티의 잦은 변경을 막기 위해 400 에러 발생
2. User 엔티티의 변경은 막되, 에러 발생과 실제 변경 없이 성공 반환
3. 요청이 들어올 때마다 그냥 변경
일단은 1번으로 구현을 해놓은 상황인데 더 좋은 아이디어나 이유가 있다면 코멘트 부탁드립니다!

[FEAT] 사용자의 대표 업적 변경 API 기능 개발

---

src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java

[REFACT] 프로젝트, 프로필 카드 리스트 정렬 시, 마지막 원소를 제외하고 랜덤 정렬하도록 수정

---

src/main/java/io/oeid/mogakgo/core/properties/JwtProperties.java
src/test/java/io/oeid/mogakgo/core/support/WithMockCustomUser.java
src/test/java/io/oeid/mogakgo/core/support/WithMockCustomUserSecurityContextFactory.java

- 테스트용 유저 어노테이션을 구현했습니다.
- `@WithMockCustomUser`을 사용하면 테스트에서 인증이 가능합니다!
- close #203 
- 컨트롤러 테스트를 작성할때 `.with(csrf())`를 꼭 작성해줘야합니다! 작성하지 않으면 어노테이션이 작동하지 않아요..

[FEAT] 테스트용 유저 인증 어노테이션 구현

---

src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java

[BUG] 프로젝트, 프로필 카드 리스트 랜덤 정렬 시, 2개 이하의 리스트에 대해 발생하는 예외 처리

---

src/main/java/io/oeid/mogakgo/common/swagger/template/ProfileCardSwagger.java
src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/profile/presentation/ProfileCardController.java
src/main/java/io/oeid/mogakgo/domain/profile/presentation/dto/res/UserProfileInfoAPIRes.java

[REFACT] 선택한 구역에 대한 프로필 카드 리스트 조회 API 리팩토링

---

src/main/java/io/oeid/mogakgo/common/swagger/template/ProjectSwagger.java
src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailInfoAPIRes.java

- close #245 
- 사용자의 `userId` 를 통해 해당 사용자가 현재 생성한 프로젝트를 조회하도록 구현하는 과정에서, 해당 사용자가 프로젝트를 생성하지 않아서 조회가 안되는 경우에 대해 빈 데이터를 전달하도록 했습니다! 해당 API는 1개 이상의 프로젝트를 조회하는 경우는 존재하지 않지만 빈 값만 전달해주는 것보다 데이터를 한 번 묶어서 전달하는 게 좋을 것 같아 아래 응답 형식으로 반환하도록 구현했습니다! 이 부분 관련해서 더 좋은 생각이 있는지 피드백 부탁드립니다~!
```json
{
"response": []
}
```

[FEAT] 사용자가 생성한 최신 프로젝트 상세 조회 API 개발

---

src/main/java/io/oeid/mogakgo/domain/project/application/ProjectService.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustom.java
src/main/java/io/oeid/mogakgo/domain/project/infrastructure/ProjectRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/ProjectController.java
src/main/java/io/oeid/mogakgo/domain/project/presentation/dto/res/ProjectDetailInfoAPIRes.java

[REFACT] 사용자의 프로젝트 조회 API 리팩토링

---

src/main/java/io/oeid/mogakgo/domain/project_join_req/infrastructure/ProjectJoinRequestRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/project_join_req/presentation/dto/res/ProjectJoinRequestDetailAPIRes.java

[BUG] 사용자의 프로젝트 요청 리스트 조회 시, 페이지네이션이 제대로 작동하지 않아요!

---

src/main/java/io/oeid/mogakgo/domain/auth/jwt/JwtAuthenticationFilter.java
src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
src/main/java/io/oeid/mogakgo/domain/user/util/UserGithubUtil.java

- 기존 동기처리 방식으로 순차적으로 Github API에서 언어 정보를 호출하던 방식에서 비동기 호출 후 종합 방식으로 리펙토링을 진행했습니다.
- 19개 레포를 갖고 있는 제 ID 기준 3.986 sec -> 1.295 sec (67.5%) 성능 향상을 이뤄냈습니다.
- close #261

Refact/#261 UserGithubUtil 리펙토링

---

src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementEventService.java

[BUG] 업적 이력 이벤트 발행과 재시도 처리가 제대로 작동하지 않아요!

---

src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementSocketService.java
src/main/java/io/oeid/mogakgo/domain/achievement/handler/AchievementSocketHandler.java

[REFACT] 클라이언트와의 웹 소켓 연결 후, 클라이언트의 요청을 수신해서 세션을 저장하도록 리팩토링

---

src/main/java/io/oeid/mogakgo/exception/GlobalExceptionHandler.java

- `GlobalExceptionHandler` 디버그 라벨 로그를 추가했습니다.
- close #301

log/#301 `GlobalExceptionHandler` 로그 추가

---

src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementSocketService.java
src/main/java/io/oeid/mogakgo/domain/achievement/domain/entity/vo/UserId.java
src/main/java/io/oeid/mogakgo/domain/achievement/handler/AchievementSocketHandler.java

[REFACT] 소켓 연결 후 세션 처리 로직 리팩토링 및 progressCount NPE 해결

---

src/main/java/io/oeid/mogakgo/common/aop/AchievementEventAspect.java
src/main/java/io/oeid/mogakgo/common/event/handler/AchievementEventHandler.java
src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementEventService.java
src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementFacadeService.java
src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementProgressService.java
src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
src/main/java/io/oeid/mogakgo/domain/achievement/application/dto/res/UserAchievementInfoRes.java
src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/user/application/UserAchievementService.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/UserController.java
src/main/java/io/oeid/mogakgo/domain/user/presentation/dto/res/UserAchievementUpdateApiResponse.java

[REFACT] 사용자의 대표 업적 변경 API 수정

---

src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/user/application/UserService.java
src/main/java/io/oeid/mogakgo/domain/user/domain/enums/DevelopLanguage.java
src/main/java/io/oeid/mogakgo/domain/user/util/UserGithubUtil.java
src/test/java/io/oeid/mogakgo/domain/user/application/UserServiceTest.java

- 사용자의 레포지토리가 존재하지 않을때 500에러 발생 수정
- 사용자의 업적 진행도를 포함한 업적 상세 조회 리스트에서 누적되는 업적에 대한 로직 수정
- close

alpha .4 main <- develop

---

src/main/java/io/oeid/mogakgo/domain/profile/application/ProfileCardService.java
src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java

[BUG] 선택한 구역에 대한 프로필 리스트 조회에서 페이지네이션이 제대로 작동하지 않아요!

---

src/main/java/io/oeid/mogakgo/common/aop/AchievementEventAspect.java
src/main/java/io/oeid/mogakgo/domain/profile/infrastructure/ProfileCardRepositoryCustomImpl.java

[BUG] 업적 달성 관련 오류 수정, 비회원 프로필 리스트 페이지네이션 오류 수정

---

src/main/java/io/oeid/mogakgo/scheduler/FinishedProjectScheduler.java

- 프로젝트 종료시 채팅방도 함께 종료하도록 스케쥴러를 추가했습니다.
- close #350

[FEAT] 프로젝트 종료시 채팅방 종료 스케쥴링 추가

---

src/main/java/io/oeid/mogakgo/domain/achievement/application/AchievementService.java
src/main/java/io/oeid/mogakgo/domain/achievement/application/dto/res/UserAchievementInfoRes.java
src/main/java/io/oeid/mogakgo/domain/achievement/infrastructure/UserAchievementRepositoryCustomImpl.java
src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/AchievementInfoAPIRes.java
src/main/java/io/oeid/mogakgo/domain/achievement/presentation/dto/res/UserAchievementDetailAPIRes.java

[REFACT] 사용자의 업적 상세 조회 시, 업적의 progressLevel 필드도 같이 전달하도록 추가
